version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - ${MONGODB_EXTERNAL_PORT}:${MONGODB_INTERNAL_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    networks:
      - gym_network
    volumes:
      - mongo:/var/lib/mongo
      - mongodb:/data/db
      - mongo_config:/data/configdb

  workload:
    image: workload:latest
    build: ./workload-service
    container_name: workload
    restart: on-failure
    env_file: ./.env
    ports:
      - ${WORKLOAD_SERVER_EXTERNAL_PORT}:${WORKLOAD_SERVER_INTERNAL_PORT}
    environment:
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_EXTERNAL_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@${MONGODB_HOST}:${MONGODB_INTERNAL_PORT}/${MONGODB_DB}?authSource=admin
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - gym_network
    volumes:
      - workload:/var/lib/workload

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RABBITMQ_EXTERNAL_PORT}:${RABBITMQ_INTERNAL_PORT}
    networks:
      - gym_network
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  mysqldb:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - gym_network
    volumes:
      - mysql:/var/lib/mysql

  gym:
    image: gym:latest
    build: ./gym
    container_name: gym
    restart: unless-stopped
    ports:
      - ${GYM_SERVER_EXTERNAL_PORT}:${GYM_SERVER_INTERNAL_PORT}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:${MYSQL_EXTERNAL_PORT}/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_EXTERNAL_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - gym_network
    depends_on:
      - mysqldb
      - rabbitmq
    volumes:
      - gym:/var/lib/gym

volumes:
  gym:
  workload:
  mongo:
  mongodb:
  mongo_config:
  mysql:
  rabbitmq:

networks:
  gym_network:
